---
- name: Installs Gerrit Code Review
  hosts: all
  become: true
  strategy: debug
  vars:
    - gerrit_auth_type: DEVELOPMENT_BECOME_ANY_ACCOUNT
    - gerrit_db_info:
#        - host: localhost
#          type: h2
#          db: db/ReviewDB
#          user: gerrit
#          pass: gerrit
        - host: localhost
          type: mysql
          db: reviewdb
          user: gerrit
          pass: gerrit
    - gerrit_vagrant_install: true
    - install_mysql: true
  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk
    - role: ansible-apache2
    - role: ansible-mariadb-mysql
      when: install_mysql is defined and install_mysql
    - role: ansible-gerrit
  tasks:
